services:
  - type: web
    name: ai-doctor
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
